name: Build and push to Dockerhub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build
        run: docker build -t robertbaboi/basic-java8-release .

      - name: Push
        run: docker push robertbaboi/basic-java8-release
